version: '3.8'

services:
  proxy:
    container_name: invitation-list-proxy
    build:
      context: ./proxy
      dockerfile: ./Dockerfile
    networks:
      - invitation-list-network
    ports:
      - 80:80
    depends_on:
      - client
      - server
      - pgadmin

  client:
    container_name: invitation-list-client
    build:
      context: ./client
      dockerfile: ./Dockerfile
      target: dev
    volumes:
      - ./client:/src/client
    networks:
      - invitation-list-network
    depends_on:
     - server

  server:
    container_name: invitation-list-server
    build:
      context: ./server
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: postgres
    ports:
      - 9229:9229 # for debugger
    networks:
      - invitation-list-network
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    restart: unless-stopped

  db:
    container_name: invitation-list-db
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - invitation-list-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: invitation-list-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test
    ports:
      - 3456:80
    networks:
      - invitation-list-network
    depends_on:
      - db
    restart: unless-stopped

networks:
  invitation-list-network:
