import Head from "next/head";
import { useRouter } from "next/router";
import { InvitationPage as InvitationPageContent } from "../../modules/invitation";

const InvitationPage = () => {
	const router = useRouter();

	const { id: rawId } = router.query;
	const id = (rawId as string) ?? "";

	return (
		<>
			<Head>
				<title>You are invited! - Invitation list</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<InvitationPageContent id={id} />
		</>
	);
};

export default InvitationPage;
